variable "name_prefix" {}
variable "asg_name" {}
variable "instance_type" {}
variable "image_id" {}
variable "key" {}
variable "device_name" {}
variable "volume_size" {}
variable "volume_type" {}
variable "max_size" {}
variable "min_size" {}
variable "elb_name" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "health_check_type" {}
variable "elb_id" {}
variable "policy_type" {}
variable "aspolicy_name" {}
variable "adjustment_type" {}
variable "cooldown" {}
variable "scaling_adjustment" {}
variable "target_value" {}
variable "elb-sg-id" {}